name: PocketHungerGames
main: PHG\Loader
version: "1.0.0dev"
api: [1.13.0]
author: Imagical Corporation
description: A rewrite of the popular PocketHungerGames plugin.
website: http://imagicalcorp.github.io/PocketHungerGames
